"""empty message

Revision ID: 991edd4a57c6
Revises: f045943198d5
Create Date: 2020-11-05 18:11:55.939847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991edd4a57c6'
down_revision = 'f045943198d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    # ### end Alembic commands ###
